# Generated by Django 5.2.1 on 2025-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('juego_o_significado', models.CharField(max_length=200)),
                ('nivel_minimo', models.CharField(choices=[('EVERYONE', 'Everyone'), ('VIPS', 'Vips'), ('MODS', 'Mods'), ('SUPERMODS', 'SuperMods'), ('STREAMER', 'Streamer')], default='EVERYONE', max_length=200)),
            ],
        ),
    ]
