# Generated by Django 5.2.1 on 2025-10-31 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='notas',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notas',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notas',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
    ]
