# Generated by Django 5.2.1 on 2025-11-01 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nota_delete_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='baneos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('fecha_baneo', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('desbaneo', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baneos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
