# Generated by Django 5.2.1 on 2025-11-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_baneos_user_alter_nota_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baneos',
            options={'ordering': ['-fecha_baneo'], 'verbose_name': 'Baneo', 'verbose_name_plural': 'Baneos'},
        ),
    ]
