# Generated by Django 5.2.1 on 2025-11-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_baneos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalTwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del canal de Twitch', max_length=100, unique=True)),
                ('streamer', models.CharField(help_text='Nombre del streamer/dueño del canal', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Notas sobre el canal o reglas especiales', null=True)),
                ('url_twitch', models.URLField(blank=True, null=True)),
                ('color_distintivo', models.CharField(default='#9147ff', help_text='Color hex para identificar el canal', max_length=7)),
                ('activo', models.BooleanField(default=True, help_text='¿Sigues siendo mod en este canal?')),
                ('fecha_inicio_moderacion', models.DateTimeField(auto_now_add=True)),
                ('total_comandos', models.IntegerField(default=0, editable=False)),
                ('total_baneos_activos', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Canal de Twitch (Moderación)',
                'verbose_name_plural': 'Canales de Twitch (Moderación)',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='comando',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Nota de Moderación', 'verbose_name_plural': 'Notas de Moderación'},
        ),
        migrations.AddField(
            model_name='comando',
            name='activo',
            field=models.BooleanField(default=True, help_text='¿El comando está activo en el canal?'),
        ),
        migrations.AddField(
            model_name='comando',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comando',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REGLA', 'Regla del Canal'), ('INCIDENTE', 'Incidente'), ('RECORDATORIO', 'Recordatorio'), ('VIEWER', 'Info de Viewer')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='comando',
            name='juego_o_significado',
            field=models.CharField(help_text='Descripción o respuesta del comando', max_length=200),
        ),
        migrations.AlterField(
            model_name='comando',
            name='nombre',
            field=models.CharField(help_text='Ej: !hola, !reglas, !discord', max_length=200),
        ),
        migrations.AlterField(
            model_name='nota',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ej: troll, spam, viewer-vip', max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='importante',
            field=models.BooleanField(default=False, help_text='Marcar para referencia rápida'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.TextField(help_text='Detalles de la nota, incidente, regla, etc.'),
        ),
        migrations.AddField(
            model_name='baneos',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baneos', to='core.canaltwitch'),
        ),
        migrations.AddField(
            model_name='comando',
            name='canal',
            field=models.ForeignKey(help_text='Canal donde aplica este comando', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='core.canaltwitch'),
        ),
        migrations.AddField(
            model_name='nota',
            name='canal',
            field=models.ForeignKey(help_text='Canal al que pertenece esta nota', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.canaltwitch'),
        ),
        migrations.AlterUniqueTogether(
            name='comando',
            unique_together={('canal', 'nombre')},
        ),
    ]
