# Generated by Django 5.2.1 on 2025-11-03 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_canaltwitch_alter_comando_options_alter_nota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baneos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='carrucel_inicio', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
