# Generated by Django 5.2.1 on 2025-11-03 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_baneos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baneos',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen relacionada con el baneo', null=True, upload_to='baneos/imagenes/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
